export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADED = "PROFILE_LOADED";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILES_LOADED = "PROFILES_LOADED";
export const GET_GITHUB_REPOS = "GET_GITHUB_REPOS";
export const GITHUB_REPOS_LOADED = "GITHUB_REPOS_LOADED";
export const GET_POSTS = "GET_POSTS";
export const POSTS_LOADED = "POSTS_LOADED";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const ADD_LIKE = "ADD_LIKE";
export const REMOVE_LIKE = "REMOVE_LIKE";
export const DELETE_POST = "DELETE_POST";
export const POST_DELETED = "POST_DELETED";
export const ADD_POST = "ADD_POST";
export const POST_ADDED = "POST_ADDED";
export const GET_POST = "GET_POST";
export const POST_LOADED = "POST_LOADED";
export const ADD_COMMENT = "ADD_COMMENT";
export const COMMENT_ADDED = "COMMENT_ADDED";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const COMMENT_REMOVED = "COMMENT_REMOVED";


//apnidukaan auth
export const LOAD_SELLER = "LOAD_SELLER"
export const SELLER_LOADED = "SELLER_LOADED"
export const SELLER_LOAD_ERROR = "SELLER_LOAD_ERROR"
export const LOAD_BUYER = "LOAD_BUYER"
export const BUYER_LOADED = "BUYER_LOADED"
export const BUYER_LOAD_ERROR = "BUYER_LOAD_ERROR"
export const LOGIN_BUYER = "LOGIN_BUYER"
export const LOGIN_SELLER = "LOGIN_SELLER"
export const BUYER_LOGIN_SUCCESS = "BUYER_LOGIN_SUCCESS"
export const SELLER_LOGIN_SUCCESS = "SELLER_LOGIN_SUCCESS"
export const BUYER_LOGIN_FAIL = "BUYER_LOGIN_FAIL"
export const SELLER_LOGIN_FAIL = "SELLER_LOGIN_FAIL"
export const BUYER_LOGOUT = "BUYER_LOGOUT"
export const BUYER_ACCOUNT_DELETED = "BUYER_ACCOUNT_DELETED"
export const SELLER_LOGOUT = "SELLER_LOGOUT"
export const SELLER_ACCOUNT_DELETED = "SELLER_ACCOUNT_DELETED"

//apnidukkaan profile
export const CREATE_BUYER_PROFILE = "CREATE_BUYER_PROFILE"
export const CREATE_SELLER_PROFILE = "CREATE_SELLER_PROFILE"
export const BUYER_PROFILE_CREATED = "BUYER_PROFILE_CREATED"
export const SELLER_PROFILE_CREATED = "SELLER_PROFILE_CREATED"
export const BUYER_PROFILE_ERROR = "BUYER_PROFILE_ERROR"
export const GET_BUYER_PROFILE = "GET_BUYER_PROFILE" 
export const GET_BUYER_PROFILES = "GET_BUYER_PROFILES" 
export const BUYER_PROFILE_LOADED = "BUYER_PROFILE_LOADED" 
export const CLEAR_BUYER_PROFILE = "CLEAR_BUYER_PROFILE" 
export const UPDATE_BUYER_PROFILE = "UPDATE_BUYER_PROFILE" 
export const BUYER_PROFILE_UPDATED = "BUYER_PROFILE_UPDATED"
export const BUYER_PROFILES_LOADED = "BUYER_PROFILES_LOADED" 
export const GET_SELLER_PROFILE = "GET_SELLER_PROFILE" 
export const SELLER_PROFILE_LOADED = "SELLER_PROFILE_LOADED" 
export const SELLER_PROFILE_ERROR = "SELLER_PROFILE_ERROR" 
export const CLEAR_SELLER_PROFILE = "CLEAR_SELLER_PROFILE" 
export const UPDATE_SELLER_PROFILE = "UPDATE_SELLER_PROFILE" 
export const SELLER_PROFILE_UPDATED = "SELLER_PROFILE_UPDATED"
export const GET_SELLER_PROFILES = "GET_SELLER_PROFILES" 
export const SELLER_PROFILES_LOADED = "SELLER_PROFILES_LOADED" 
export const SELLER_PROFILES_ERROR = "SELLER_PROFILES_ERROR";
export const BUYER_PROFILE_NOT_FOUND = "BUYER_PROFILE_NOT_FOUND"
export const SELLER_PROFILE_NOT_FOUND = "SELLER_PROFILE_NOT_FOUND"

//orders

export const CREATE_ORDER = "CREATE_ORDER"
export const ORDER_CREATED = "ORDER_CREATED"
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR"
export const GET_SELLER_ORDERS = "GET_SELLER_ORDERS"
export const SELLER_ORDERS_LOADED = "SELLER_ORDERS_LOADED"
export const SELLER_ORDERS_ERROR = "SELLER_ORDERS_ERROR"
export const GET_BUYER_ORDERS = "GET_BUYER_ORDERS"
export const BUYER_ORDERS_LOADED = "BUYER_ORDERS_LOADED"
export const BUYER_ORDERS_ERROR = "BUYER_ORDERS_ERROR"
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS"
export const ORDER_STATUS_UPDATED = "ORDER_STATUS_UPDATED"

//products
export const GET_LOGGED_SELLER_PRODUCTS = "GET_LOGGED_SELLER_PRODUCTS"
export const LOGGED_SELLER_PRODUCTS_LOADED = "LOGGED_SELLER_PRODUCTS_LOADED"
export const LOGGED_SELLER_PRODUCTS_ERROR = "LOGGED_SELLER_PRODUCTS_ERROR"

export const ADD_PRODUCT = "ADD_PRODUCT"
export const PRODUCT_ADDED = "PRODUCT_ADDED"
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR"
export const GET_PRODUCT_USING_ID = "GET_PRODUCT_USING_ID"
export const PRODUCT_LOADED_USING_ID = "PRODUCT_LOADED_USING_ID"
export const PRODUCT_ERROR_USING_ID = "PRODUCT_ERROR_USING_ID"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const PRODUCT_UPDATED = "PRODUCT_UPDATED";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_DELETED = "PRODUCT_DELETED";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export const GET_ALL_SELLERS_PRODUCTS = "GET_ALL_SELLERS_PRODUCTS";
export const ALL_SELLERS_PRODUCTS_LOADED = "ALL_SELLERS_PRODUCTS_LOADED";
export const ALL_SELLERS_PRODUCTS_ERROR = "ALL_SELLERS_PRODUCTS_ERROR";


//Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const ADDED_TO_CART = "ADDED_TO_CART";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

export const GET_BUYER_CART = "GET_BUYER_CART";
export const BUYER_CART_LOADED = "BUYER_CART_LOADED";
export const GET_BUYER_CART_ERROR = "GET_BUYER_CART_ERROR";

    